/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import GameScreen.GameInit;
import audio.Som;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Menu2 extends javax.swing.JFrame {

    int birdNumero;

    public void iniciarJogo(int birdNumero) {
        GameInit main = new GameInit(birdNumero);
        this.setVisible(false);
    }

    /**
     * Creates new form menu2
     */
    public Menu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EscolhaPersonagem = new javax.swing.JPanel();
        Patrick = new javax.swing.JLabel();
        Yuri = new javax.swing.JLabel();
        Francine = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Angelo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Sergio = new javax.swing.JLabel();
        patrick = new javax.swing.JButton();
        yuri = new javax.swing.JButton();
        angelo = new javax.swing.JButton();
        francine = new javax.swing.JButton();
        marcos = new javax.swing.JButton();
        Marcos = new javax.swing.JLabel();
        sergio = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flappy Angelo");

        EscolhaPersonagem.setToolTipText("Flappy Angelo");
        EscolhaPersonagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Patrick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Birds/PatrickBird.png"))); // NOI18N
        EscolhaPersonagem.add(Patrick, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        Yuri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Birds/YuriBird.png"))); // NOI18N
        EscolhaPersonagem.add(Yuri, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        Francine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Birds/FrancineBird.png"))); // NOI18N
        EscolhaPersonagem.add(Francine, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));
        EscolhaPersonagem.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 104, -1, -1));

        Angelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Birds/AngeloBird.png"))); // NOI18N
        EscolhaPersonagem.add(Angelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EscolhaPersonagem.png"))); // NOI18N
        EscolhaPersonagem.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 463, 59));

        Sergio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Birds/SergioBird.png"))); // NOI18N
        EscolhaPersonagem.add(Sergio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        patrick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Names/Tortuguita.png"))); // NOI18N
        patrick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patrickActionPerformed(evt);
            }
        });
        EscolhaPersonagem.add(patrick, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 130, 27));

        yuri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Names/YuriGates.png"))); // NOI18N
        yuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yuriActionPerformed(evt);
            }
        });
        EscolhaPersonagem.add(yuri, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 450, 110, 26));

        angelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Names/FlappyAngelo.png"))); // NOI18N
        angelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angeloActionPerformed(evt);
            }
        });
        EscolhaPersonagem.add(angelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 120, 30));

        francine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Names/BichoPapao.png"))); // NOI18N
        francine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                francineActionPerformed(evt);
            }
        });
        EscolhaPersonagem.add(francine, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 120, 29));

        marcos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Names/Waldemarzino.png"))); // NOI18N
        marcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcosActionPerformed(evt);
            }
        });
        EscolhaPersonagem.add(marcos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 120, 26));

        Marcos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Birds/MarcosBird_1.png"))); // NOI18N
        EscolhaPersonagem.add(Marcos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        sergio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Names/MoustacheBoy.png"))); // NOI18N
        sergio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sergioActionPerformed(evt);
            }
        });
        EscolhaPersonagem.add(sergio, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 450, 130, 31));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fundo.png"))); // NOI18N
        EscolhaPersonagem.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EscolhaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EscolhaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void marcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcosActionPerformed
//********************** WALDEMARZINHO SELECTED
        Som som = new Som();
        som.play("Click");
        birdNumero = 3;
        iniciarJogo(birdNumero);


    }//GEN-LAST:event_marcosActionPerformed

    private void francineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_francineActionPerformed
//************************ BICHO PAPAO SELECTED        
        Som som = new Som();
        som.play("Click");
        birdNumero = 5;
        iniciarJogo(birdNumero);


    }//GEN-LAST:event_francineActionPerformed

    private void yuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yuriActionPerformed
//*********************** YURI GATES SELECTED        
        Som som = new Som();
        som.play("Click");
        birdNumero = 4;
        iniciarJogo(birdNumero);


    }//GEN-LAST:event_yuriActionPerformed

    private void sergioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sergioActionPerformed
//*********************** MUSTACHE MAN SELECTED
        Som som = new Som();
        som.play("Click");
        birdNumero = 6;
        iniciarJogo(birdNumero);


    }//GEN-LAST:event_sergioActionPerformed

    private void patrickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patrickActionPerformed

        //******* TORTUGUITA SELECTED
        Som som = new Som();
        som.play("Click");
        birdNumero = 1;
        iniciarJogo(birdNumero);


    }//GEN-LAST:event_patrickActionPerformed

    private void angeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angeloActionPerformed
//****************************** ANGELO BIRD SELECTED        
        Som som = new Som();
        som.play("Click");
        birdNumero = 2;
        iniciarJogo(birdNumero);

    }//GEN-LAST:event_angeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Angelo;
    private javax.swing.JPanel EscolhaPersonagem;
    private javax.swing.JLabel Francine;
    private javax.swing.JLabel Marcos;
    private javax.swing.JLabel Patrick;
    private javax.swing.JLabel Sergio;
    private javax.swing.JLabel Yuri;
    private javax.swing.JButton angelo;
    private javax.swing.JButton francine;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton marcos;
    private javax.swing.JButton patrick;
    private javax.swing.JButton sergio;
    private javax.swing.JButton yuri;
    // End of variables declaration//GEN-END:variables
}
